name: Code Format Check

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff pydocstyle pyupgrade

      - name: Check Python code formatting with Black
        run: |
          black --check --diff .

      - name: Check imports with isort
        run: |
          isort --check --diff --profile black .

      - name: Check code with Ruff (unused imports, blank lines)
        run: |
          ruff check --select=E,F,W,I001 --ignore=E501,E203 .

      - name: Check docstrings with pydocstyle
        run: |
          pydocstyle --ignore=D100,D104,D203,D212 .
        continue-on-error: true  # Don't fail the build yet, just report

      - name: Check Python syntax upgrades
        run: |
          pyupgrade --py38-plus --check $(find . -name "*.py")
        continue-on-error: true  # Don't fail the build yet, just report

      - name: Check Markdown files
        if: always()  # Run this step even if previous steps fail
        run: |
          npm install -g markdownlint-cli
          markdownlint '**/*.md' --ignore node_modules

      - name: Check JSON files formatting
        if: always()  # Run this step even if previous steps fail
        run: |
          npm install -g prettier
          prettier --check "**/*.json"
