name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Install Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4

    - name: Generate Gradle Wrapper
      run: gradle wrapper
      
    - name: Setup Gradle Wrapper Executable
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    # Upload step removed to avoid artifact action issues 