[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.eggs
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.ruff]
line-length = 88
target-version = "py38"
select = ["E", "F", "W", "I001"]
ignore = ["E501", "E203"]
unfixable = []

[tool.ruff.isort]
known-first-party = ["bot", "engine", "scraper"]

[tool.pydocstyle]
ignore = ["D100", "D104", "D203", "D212", "D213"]
match = "(?!test_).*\\.py"
